src/AppBundle/Entity/Author.php
<?php
namespace AppBundle\Entity;

use AppBundle\Entity\Book;
use Doctrine\ORM\Mapping as ORM;
use Doctrine\Common\Collections\ArrayCollection;


/**
 * Author
 *
 * @ORM\Table(name="author")
 * @ORM\Entity(repositoryClass="AppBundle\Repository\AuthorRepository")
 */
class Author
{
    /**
     * @var int
     *
     * @ORM\Column(name="id", type="integer")
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    private $id;

    /**
     * @var string
     *
     * @ORM\Column(name="first_name", type="string", length=255)
     */
    private $firstName;


    /**
     * @var string
     *
     * @ORM\Column(name="sur_name", type="string", length=255)
     */
    private $surName;
    
    
    /**
     * @ORM\ManyToMany(targetEntity="\AppBundle\Entity\Book", mappedBy="authors", fetch="EXTRA_LAZY")
     */
    protected $books;
    
    
    public function __construct()
    {
        $this->books = new ArrayCollection();
    }
    
    public function getBooks()
    {
        return $this->books;
    }
    
    
    public function addBook(Book $book) 
    {
        $this->books[] = $book;
        
        return $this;
    }
    
    
    public function removeBook(Book $book)
    {
        $this->books->removeElement($book);
        $book->setGenre(null);
    }


    /**
     * Get id
     *
     * @return int
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Set firstName
     *
     * @param string $firstName
     *
     * @return Author
     */
    public function setFirstName($firstName)
    {
        $this->firstName = $firstName;

        return $this;
    }

    /**
     * Get firstName
     *
     * @return string
     */
    public function getFirstName()
    {
        return $this->firstName;
    }

    /**
     * Set surName
     *
     * @param string $surName
     *
     * @return Author
     */
    public function setSurName($surName)
    {
        $this->surName = $surName;

        return $this;
    }

    /**
     * Get surName
     *
     * @return string
     */
    public function getSurName()
    {
        return $this->surName;
    }
    
    
    public function __toString() 
    {
        return $this->getFullName();
    }
    
    
    public function getFullName()
    {
        return $this->getFirstName()." ".$this->getSurName();
    }
}

src/AppBundle/Controller/FilterController.php
<?php

namespace AppBundle\Controller;

use Sensio\Bundle\FrameworkExtraBundle\Configuration\Route;
use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use Symfony\Component\HttpFoundation\Request;
use AppBundle\Entity\Book;
use AppBundle\Form\Type\SearchBookType;


class FilterController extends Controller
{
    /**
     * @Route("/books_page", name="books_page")
     */
    public function indexAction(Request $request)
    {
        $em = $this->getDoctrine();
        
        $books = $em->getRepository(Book::class)->findAll();
        
        return $this->render('AppBundle:Filter:books.html.twig', [
            'books' => $books,           
        ]);
    }
    
    
    /**
     * @Route("/searchBar", name="search_book")
     */
    public function searchBarAction()
    {
        $searchBookForm = $this->createForm(SearchBookType::class);
        
        return $this->render('AppBundle:Form:searchBookForm.html.twig', [
            'form' => $searchBookForm->createView(),
        ]);
    }
    
    
    /**
     * @Route("/search_book_result", name="handle_search_book")
     */
    public function handleSearchForm(Request $request)
    {   
        $form = $this->createForm(SearchBookType::class);
        
        $form->handleRequest($request);
        
        if ($form->isSubmitted() && $form->isValid()) {
            
            $data = $form->getData();

            $em = $this->getDoctrine();
            
            $books = $em->getRepository(Book::class)
                ->searchBookByParam($data['genre'], $data['book_title'], $data['author']);
            
            
            return $this->render('AppBundle:Filter:books.html.twig', [
                'books' => $books,
            ]);
        }
    }

}

src/AppBundle/Resources/views/Filter/books.html.twig
{% extends 'base.html.twig' %}
        
{% block title %} Books Page {% endblock %}

{% block stylesheets %} {{ parent() }} {% endblock %}
    
{% block content %}
    
<nav class="navbar navbar-default navbar-static-top" role="navigation">
    <div class="container">
        
        {{ render(controller('AppBundle:Filter:searchBar')) }}
        
    </div>
</nav>
    
    <h1>Books Page</h1>                                                                            
    
    
        <div class="col-xs-12 col-md-12">
                    
            {% if books %}

            <table class="table table-bordered table-hover">
                <tr>
                    <th>ID</th>
                    <th>Title</th>
                    <th>Isbn</th>
                    <th>Genre</th>
                    <th>Author</th>
                </tr>

                {% for book in books %}
                    <tr>
                        <td>{{ book.id }}</td>
                        <td>{{ book.title }}</td>
                        <td>{{ book.isbn }}</td>
                        <td>{{ book.genre }}</td>
                        <td>
                            {% for author in book.authors %}
                                {{ author.fullName }}{% if loop.index != loop.last %}, {% endif %}
                            {% endfor %}
                        </td>
                    </tr>
                {% endfor %}
            </table>

            {% else %}

                <h3>No Search Result</h3>

            {% endif %}
        </div>
    
{% endblock %}